server:
  port: 9999
spring:
  application:
    name: es-article

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leadnews_article?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
# 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.heima.model.article.pojo


#自定义elasticsearch连接配置
elasticsearch:
  host: 119.96.97.234
  port: 9200

minio:
  accessKey: admin
  secretKey: admin123
  bucket: leadnews
  endpoint: http://154.22.117.165:9000
  readPath: http://154.22.117.165:9000